//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.10 at 01:13:06 AM GMT 
//

package ie.gmit.sw.Model;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="custID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="first" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "custID", "first", "lastname", "email" })
@XmlRootElement(name = "customer")
public class Customer implements Serializable {

	protected int custID;
	@XmlElement(required = true)
	protected String first;
	@XmlElement(required = true)
	protected String lastname;
	@XmlElement(name = "Email", required = true)
	protected String email;

	public Customer() {
		super();
	}

	public Customer(int custID, String first, String lastname, String email) {
		super();
		this.custID = custID;
		this.first = first;
		this.lastname = lastname;
		this.email = email;
	}

	/**
	 * Gets the value of the custID property.
	 * 
	 */
	public int getCustID() {
		return custID;
	}

	/**
	 * Sets the value of the custID property.
	 * 
	 */
	public void setCustID(int value) {
		this.custID = value;
	}

	/**
	 * Gets the value of the first property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFirst() {
		return first;
	}

	/**
	 * Sets the value of the first property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setFirst(String value) {
		this.first = value;
	}

	/**
	 * Gets the value of the lastname property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLastname() {
		return lastname;
	}

	/**
	 * Sets the value of the lastname property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setLastname(String value) {
		this.lastname = value;
	}

	/**
	 * Gets the value of the email property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * Sets the value of the email property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setEmail(String value) {
		this.email = value;
	}

}
